export default {
    home: require('../assets/icons/form.png'),
    calendar: require('../assets/icons/calendar.png'),
    agenda: require('../assets/icons/agenda.png'),
    note: require('../assets/icons/notes.png'),
    mail: require('../assets/icons/mail.png'),
    card: require('../assets/icons/card.png'),
    file: require('../assets/icons/file.png'),
    fileBlank: require('../assets/icons/file-blank.png'),
    settings: require('../assets/icons/settings.png'),
    logout: require('../assets/icons/power.png'),
    menu: require('../assets/icons/menu.png'),
    sun: require('../assets/icons/sun.png'),
    // circleArrow: require('../assets/icons/circleArrow.png'),
    reply: require('../assets/icons/arrow-reply.png'),
    forward: require('../assets/icons/arrow-forward.png'),
    leftChevron: require('../assets/icons/chevron-left.png'),
    bottomChevron: require('../assets/icons/chevron-bottom.png'),
    download: require('../assets/icons/download.png'),
    inbox: require('../assets/icons/inbox.png'),
    send: require('../assets/icons/send.png'),
    draft: require('../assets/icons/note-text.png'),
    box: require('../assets/icons/box.png'),
    paperclip: require('../assets/icons/paperclip.png'),
    search: require('../assets/icons/search.png'),
    addFolder: require('../assets/icons/add-folder.png'),
    folder: require('../assets/icons/folder-opened.png'),
    password: require('../assets/icons/lock.png'),
    user: require('../assets/icons/user.png'),
    show: require('../assets/icons/eye.png'),
    hide: require('../assets/icons/eye-no.png'),
    warning: require('../assets/icons/warning.png'),
    checkedRadio: require('../assets/icons/radio-checked.png'),
    uncheckedRadio: require('../assets/icons/radio-unchecked.png'),
    notification: require('../assets/icons/bell.png'),
    notificationActive: require('../assets/icons/bell-active.png'),
    phone: require('../assets/icons/mobile.png')
}